name: QuasarUtils
version: '${version}'
main: ru.john.quasarutils.QuasarUtils
api-version: '1.16'
depend: [PlaceholderAPI, kotlin-stdlib]
commands:
  char:
    description: 'указать имя и фамилию'
    usage: /<command>
    permission: char.create
  quasarutils:
    description: 'Главная команда плагина'
    usage: /<command>
    permission: quasarutils.main